- hosts: localhost
  gather_facts: False
  vars:
     aws_region: "us-east-1"
     security_group: "ansible_tower_sg"

  tasks:  
  - debug:
       msg: 
         - "Host vars: {{ ec2 }}"
  - name: Terminate aws instance
    local_action:
        module: ec2
        region: "{{ aws_region }}"
        state: 'absent'
        instance_ids: "{{ ec2.instance_ids }}"
        wait: True

