- hosts: localhost
  gather_facts: False
  vars:
     aws_region: "us-east-1"
     security_group: "ansible_tower_sg"

  tasks:
  
  - name: Terminate aws instance
    local_action:
        module: ec2
        region: "{{ aws_region }}"
        state: 'absent'
        instance_ids: "{{ hostvars[groups['all'][0]]['instance_id'] }}"
        wait: True
  - name: Wait for the instances to be stopped by checking the ssh port
       wait_for: host="{{ hostvars[groups['all'][0]]['inventory_hostname'] }}" port=22 delay=60 timeout=320 state=stopped
