- hosts: localhost
  gather_facts: False
  vars:
     ami_id: "ami-0affd4508a5d2481b"
     aws_region: "us-east-1"

  tasks:

    - name: Provision a set of instances
      ec2:
         key_name: rwedhat-aws-keypair
         region: "{{ aws_region }}"
         instance_type: t2.micro
         image: "{{ ami_id }}"
         wait: true
         exact_count: 1
         count_tag:
            Name: CICD
         instance_tags:
            Name: CICD
      register: ec2

    - name: allocate a new elastic IP inside a VPC in us-west-2
      ec2_eip:
          device_id: "{{ item }}"
      register: eip
